### ISSUE TITLE
Support for writing spectra to files

### ISSUE THREAD

**Issue by jasonmhite** [lbl-anp/becquerel#179]
I'm interested in adding support for writing spectrum files to disk, but I need to answer some design questions first as the current implementation needs some possibly significant refactoring to support writing files in a clean way.

The implementation I would imagine is something along the lines of
```python
import becquerel as bq

spec = bq.Spectrum(...)
# do stuff... e.g. calibrate spec etc.

bq.parsers.SpeFile.write_from_spec("my_spec.spe", spec) 
```
where `write_from_spec` is a class method of each format class that gets all the required information from the passed `Spectrum` object and writes out the given spectrum. 

The main problem is that currently the `Spectrum` class does not track all of the info required to do this. Especially, spectra do not store their energy calibration coefficients. I guess these could be inferred from the calibrated energy bin edges, but it seems like just storing them in the class when they are available is far more useful. 

The alternative is to have a write function that just takes all the parameters needed for the format and have the user manually pass them. I made a prototype based on the code that's already in `SpeFile` that works by doing exactly that, but it seems redundant and requires the user to understand the details of the format. Here it is: https://gist.github.com/jasonmhite/57195ba0648fbeb2a377c9f5feb78b36 . 

Thoughts? The actual code for writing is easy as long as the required data is available. If we can settle on a design I should be able to implement at least SPE pretty quickly. 

#103 is related to this. The parser implementations are a bit messy right now and a refactoring would influence what I have to do significantly.

**Comment by jccurtis** [comment]
Hi @jasonmhite, Thanks for the feedback! You are absolutely correct in saying that the file IO code need refactoring as this was added early on (before the `Spectrum` class, etc.) @markbandstra is most familiar with this code so he is probably the best resource for how we could refactor this code but for the time being:

1. Good catch on the missing calibration storage in the spectrum object. This is an oversight which, upon further reflection, dates back to a circular dependency between the `Calibration` and `Spectrum` definitions. Either way we should resolve this before the file IO can be implemented (see #180).
2. Your gist looks good. I propose adding that functionality to the `SpeFile` class for now under a `write` method that takes a `Spectrum` as an argument. In addition lets add a `write` method to the `Spectrum` object which takes a `filename` as an argument and writes to a file type based on the extension. This extension selection should be a function in the parsers under a generic `_write_file` function which internally selects the correct parser to use and passes the `Spectrum` to it. 

In general, the file IO classes may not store all the spectrum data and metadata in its raw form and instead should always populate a `Spectrum` object instead. All extra fields which otherwise are not members of a`Spectrum` can go into a `dict` in the `Spectrum` object called `metadata` or something of the sort.

Let me know what you think and thanks again!

**Comment by jasonmhite** [comment]
Sounds good. So for the moment, I will tidy up the code I wrote and prepare a pull request to add it to the `SpeFile` implementation. After that, I will look into #180 as a first step towards a more polished implementation.

**Comment by jasonmhite** [comment]
As part of this, I discovered that the existing code does not handle the ROI block correctly. Should I fix this as part of my pull request or break it out into a separate issue?

**Comment by markbandstra** [comment]
Hi @jasonmhite , thanks for finding that. Could you file a separate issue describing the bug so we have it clearly documented? You can fix that issue as part of your PR. Thanks!

**Comment by jccurtis** [comment]
@markbandstra will #244 clean up the file parsing?

**Comment by markbandstra** [comment]
@jccurtis Yes, I would like to clean up the inheritance structure of the parsers in #244, however my vision was to abandon the idea of ever outputting into those formats and focus only on output to hdf5. In my mind it seems like that choice will make the overall task simpler, but I could be wrong as I haven't gotten that far.
