### ISSUE TITLE
End support for Python 2.7 by end of 2020

### ISSUE THREAD

**Issue by markbandstra** [lbl-anp/becquerel#182]
This decision will align becquerel with a large portion of the open source community:
https://python3statement.org

Python 2.7 EOL notice:
https://www.python.org/dev/peps/pep-0373/#update

Tasks that we will need to do:
- [ ] Drop 2.7 from `travis.yml`
- [ ] Update classifiers in `setup.py`
- [ ] Remove `from __future__ import print_function` from code
- [ ] Add minimum python version to `requirements.txt`
- [ ] Remove `llvmlite` and `numba` version limitations

**Comment by jccurtis** [comment]
Should we wait until fitting (#50) is in before dumping `py2`?

**Comment by jccurtis** [comment]
Closed with #242

**Comment by micwoj92** [comment]
@jccurtis @markbandstra 
Hello, I didn't want to open new issue for this, but there a __future__ import https://github.com/lbl-anp/becquerel/blob/9d6d6bc27864d4dba048d1671fd9cdd4f5d56554/becquerel/io/h5.py#L3

Additionally there are several `future` imports in code, these should be no longer required, since dropping python2?
https://github.com/lbl-anp/becquerel/blob/9d6d6bc27864d4dba048d1671fd9cdd4f5d56554/becquerel/tools/nndc.py#L16
https://github.com/lbl-anp/becquerel/blob/9d6d6bc27864d4dba048d1671fd9cdd4f5d56554/becquerel/tools/isotope.py#L5
https://github.com/lbl-anp/becquerel/blob/9d6d6bc27864d4dba048d1671fd9cdd4f5d56554/becquerel/tools/wallet_cache.py#L5
https://github.com/lbl-anp/becquerel/blob/9d6d6bc27864d4dba048d1671fd9cdd4f5d56554/becquerel/core/energycal.py#L8

Are these 2 questions within scope of this issue?

**Comment by jvavrek** [comment]
The `from __future__ import annotations` enables some type hinting syntax (specifically the `|`) prior to python 3.10 (IIRC). The `future.builtins` can probably be removed.

**Comment by markbandstra** [comment]
Thanks for the sharp eyes, @micwoj92 ! I just put in a fix and we'll merge it soon. I also remove an unnecessary `from future.utils import viewitems`.

@jvavrek is correct that we need the `from __future__ import annotations` until we get to later versions of python3.

**Comment by markbandstra** [comment]
I should also remove `future` from `requirements.txt` before this PR is complete.
