### ISSUE TITLE
energy calibrations should use channel space, not bin space

### ISSUE THREAD

**Issue by jvavrek** [lbl-anp/becquerel#184]
`becquerel`  classes should work with an x-axis of channels, not bins. For example, say I have an ADC that produces a spectrum of 32768 discrete channels, but I need to rebin the spectrum by a factor of 4 to 8192 channels to trade off resolution for statistics. `becquerel` would give energy calibration gains differing by a factor of 4 for the original and rebinned spectra, because it works in the (implicit) bin space of the `spectrum` rather than the (explicit) channel space.

This is even more crucial for list-mode data (#183) with an arbitrarily large number of possible ADC values. The user may need to play around with different bin widths, and the calibration should not vary as a result.

Working in channel space would also allow the user to apply the calibration from a calibration spectrum to a production spectrum with different binning.

My current hotfix is to add a `self.binwidth` member to `autocal` and then do
```
fit = find_best_gain(self.peakfinder.channels * self.binwidth, ...)
```
because `peakfinder.channels` really returns bins, not channels, where it thinks peaks are located. This leads to difficulties down the road with plotting calibration curves, e.g., as the `peakfinder.channels` are still in bin space, not channel space. A more robust solution should therefore probably pass the spectrum bin width to the `peakfinder` and/or `spectrum` classes instead, so that by the time `autocal` is used, it is already seeing channels and not bins.

Note that working in channel space instead of bin space will not break any existing examples (e.g. `examples/autocal.ipynb`) because the binwidths there are just 1 channel/bin.

**Comment by jvavrek** [comment]
Another thought: there's no reason to restrict this generalization to an integer number of ADC channels. Imagine an analogue DAQ that returned, say, a `float` of the area under the current pulse. The user would definitely need to bin this manually, and the calibration (in keV / (mA us) or something) should properly account for the bin width.

**Comment by jccurtis** [comment]
@jvavrek all good points! These are the exact feature improvements we are looking for. My thoughts:

* A distinction between ADC channels corresponding to integrated current / resulting voltage vs spectrum histogram bins needs to be established. You have outlined this very nicely.
* I'm not sure `channel` is necessarily clear here though as this is often used interchangeably with `bin`. Please let me know if you disagree on this point. 😃 Maybe something more explicit like `adc_value` would be more clear and more concisely represent `int`/`float` values for.

In terms of reducing complexity I'm interested on hearing your thoughts on not passing `binwidth` but instead passing the `adc_channels` (`x`) and `counts` (`y`) when performing these operations. Honestly, the best course of action here might be just using the `spectrum` objects explicitly instead of tracking all this information around through `args` to function calls which are difficult to maintain. Let me know what you think!

**Comment by jvavrek** [comment]
- `adc_value` is much better than `channel`, agreed
- using the `spectrum` object is also better, agreed. I initially avoided this route pre-calibration because of the `self.is_calibrated()` check in `bin_widths()`, but didn't see that it's just a check if `self.bin_edges_kev` exists

**Comment by jccurtis** [comment]
1. ✅ 
2. Yeah all of the `calibration` of a `Spectrum` requires some cleaning because you may have the following `init` cases:
    * Spectrum
        * Only count information (which can default to `adc_values` of the bin they are in).
        * Count and `bin_edges_adc`
            * also with calibration function / params
        * Count and `bin_edges_keV`
            * There is not explicit calibration function here
            * We still want to support re-calibrating this ...
    * Listmode 
        * `adc_values`
            * with calibration function?
        * `energy_keV`
    * All of these cases could include time information as well

This is why we need #116. Ultimately you can get to a `Spectrum` object from many paths. The `is_calibrated` property should simply reflect if there is any way to provide `bin_edges_keV`.

**Comment by jccurtis** [comment]
From today's meeting:

* Implement `bin_edges_raw`
* Resolve property `channels` to ... ???
* Update channels in docstrings
* Add `bin_centers_kev` (check for this in the plotting utils)
* Resolve the `FIXME`'s

```python
edges[:-1] + np.diff(edges)/2.
```

Make it so @jvavrek !

**Comment by jvavrek** [comment]
Note: deleted branch `issue-channel-vs-bin` as it is easier to combine this issue with #187 on a single branch.
