### ISSUE TITLE
Fitting module

### ISSUE THREAD

**Issue by bplimley** [lbl-anp/becquerel#50]
For peak fitting, energy cal fitting.
To use `lmfit`.
@jccurtis to take code from GRPP as a start.

(see also #22)

@jccurtis TODO:
- [ ] Update `erf` naming
- [ ] Add warning when fit errors unknown

**Comment by cosama** [comment]
I was looking through some paper about maximum likelihood and Poisson statistics in peak fitting. I just dump this here for now, might be useful at some later point:

- Chi-square vs maximum likelihood compared: https://www.sciencedirect.com/science/article/pii/S0168900200007567
- Maximum likelihood and small signals: https://www.sciencedirect.com/science/article/pii/S0168900299002697
- Very general article about the topic: https://www.nature.com/articles/nmeth0510-338
- Different methods to perform a likelihood fit (also iterative): https://link.springer.com/article/10.1007%2Fs10909-014-1098-4

**Comment by jccurtis** [comment]
I've been building the `fitting` module in the `feature-fitting-#50` branch. I have 5 peak models so far based on the ones I have used most commonly. I still have a long list of inline TODO's (mostly short) which I'm churning through as I write an example notebook and tests. Some of these items are topics we should discuss next week:

- [ ] Handle channel / energy fitting (what are the bin edges...)
- [ ] How to handle bin width normalization. This is particularly important for calculating the are of a gaussian. In the past I have tracked the "mode" or "units" for the y data and always tried to fit in bin-width normalized units. This was troublesome so I would rather have this be more flexible (and explicit because this is a very common error I have observed people make while learning more about peak fitting).
- [ ] Plotting options
- [ ] Peak presets: I have multi gaussian models but we could have subclasses with constrained parameters for commonly fit/complex peaks in scintillators (Co57, Co60, etc)
- [ ] Parameter guessing, the parameter initialization currently occurs based on the data vectors but some improved guess work regarding the energy resolution could be very useful. I would like to use some of the low level tools from @markbandstra's auto-calibration toolkit to do this. A general function to guess the energy resolution for a vector with a peak-like feature in it could be very useful. I could do this with `scipy`'s `cwt` transform but I would rather leverage the auto-calibration functions if possible.

Eventually we should discuss a full calibration routine which uses #93 and #50 but we should get all the underlying functionality working first.

**Comment by cosama** [comment]
I use the [Exponentially Modified Gaussian](https://en.wikipedia.org/wiki/Exponentially_modified_Gaussian_distribution) or also known as the [Hypermet function](https://www.sciencedirect.com/science/article/pii/S0168583X97002292?via%3Dihub) quite often to model left and right tails of peaks.

Furthermore, I would call your `erf` function `erfc` (complementary error function, because of the `1-erf()` part).

**Comment by jccurtis** [comment]
Nice one, thanks for this. I'll get that added. I'll also change the `erf` naming as well. I'll move this to a PR and we can continue the conversation there 👍

**Comment by cosama** [comment]
I just compared the functions in the different sources. Eq. 5 in the Hypermet paper is identical to (1) in the 'Alternative forms for computation' section in the Wikipedia article. The alternative form is also identical to function in the 'Definition' section of that article with the replace `lambda = 1.0/tau` and an additional parameter for the height (h, the other version is normalized to 1).

Problems with the earlier one arise because of `tau=0` not being a valid input, but it is a possible solution. It probably is best to just use the version with lambda and circumvent the entire issue.

**Comment by thjoshi** [comment]
@jccurtis are the tools in the feature-fitting-#50 branch functional enough for use in an analysis project?

**Comment by jccurtis** [comment]
I think so, with the caveat that the input the fitters is currently designed for spectrum bin values normalized to the bin width (i.e. `counts/keV` or `cps/keV`). This means that the guesses for initial values and calculation of peak area will be incorrect based on the Gaussian formula used. I plan to make the code more flexible but haven't gotten around to it. If you have ideas or run into issues please let me know!

**Comment by jccurtis** [comment]
@cosama and I will hack this out next week!

**Comment by jvavrek** [comment]
I also have some peak fitting routines and parameter initialization heuristics I'd be happy to share. They were designed for NRF spectra in HPGe, so focus on multiplets of Gaussians on top of slowly-varying backgrounds. They're also mostly still written in ROOT C++, but I've been translating some to Python for newer work. Let me know if you'd like to discuss!

**Comment by jvavrek** [comment]
Closed by #146
